nodeLinker: node-modules

npmAuthToken: "${GITHUB_OAUTH_TOKEN}"

npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  rvohealth:
    npmAuthToken: "${GITHUB_OAUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
