import * as fs from 'node:fs'
import * as path from 'node:path'
import ts from 'typescript'
import addRootPathForCoreSpecs from '../helpers/init/addRootPathForCoreSpecs.js'
import internalSrcPath from '../helpers/internalSrcPath.js'
import { InitPsychicAppCliOptions } from '../helpers/newPsychicApp.js'

interface TsConfigStub {
  compilerOptions?: {
    paths?: Record<string, string[]>
    types?: string[]
  }
}

export default class TsConfigBuilder {
  public static build({ options }: { options: InitPsychicAppCliOptions }) {
    const tsconfigBuildPath = path.join(process.cwd(), addRootPathForCoreSpecs('tsconfig.build.json'))
    let tsconfigPath = path.join(process.cwd(), addRootPathForCoreSpecs('tsconfig.json'))

    // A tsconfig.json already present at this point was generated by something
    // other than this builder — in practice, `create-next-app` scaffolding a
    // client. Unlike the api-only boilerplate (which splits a build-only
    // tsconfig.build.json, whose `include` omits `spec`, from a dev-time
    // tsconfig.json that adds test-runner `types`), Next.js has a single
    // tsconfig.json that also drives `next build`'s own typecheck, and its
    // `include` sweeps up every `.ts` file — spec files included. Without a
    // types reference for vitest's ambient `describe`/`it` globals, that
    // typecheck fails on any spec file that relies on them instead of
    // importing from 'vitest' explicitly (e.g. a freshly generated,
    // untouched model spec stub).
    const isPreexistingTsconfig = fs.existsSync(tsconfigPath)

    if (!isPreexistingTsconfig) {
      fs.cpSync(internalSrcPath('..', 'boilerplate', 'api', 'tsconfig.build.json'), tsconfigBuildPath)
      fs.cpSync(internalSrcPath('..', 'boilerplate', 'api', 'tsconfig.json'), tsconfigPath)
      tsconfigPath = tsconfigBuildPath
    }

    const result = ts.readConfigFile(tsconfigPath, path => ts.sys.readFile(path))
    if (result.error) {
      throw new Error(
        `Failed to read tsconfig file: ${ts.formatDiagnostic(result.error, ts.createCompilerHost({}))}`,
      )
    }
    const json = (result.config || {}) as TsConfigStub

    if (!json.compilerOptions) json.compilerOptions = {}
    const compilerOptions = json.compilerOptions

    if (!compilerOptions.paths) compilerOptions.paths = {}
    const paths = compilerOptions.paths

    paths['@conf/*'] = [`./${options.confPath}/*`]
    paths['@controllers/*'] = [`./${options.controllersPath}/*`]
    paths['@models/*'] = [`./${options.modelsPath}/*`]
    paths['@serializers/*'] = [`./${options.serializersPath}/*`]
    paths['@services/*'] = [`./${options.servicesPath}/*`]
    paths['@spec/*'] = [`./${options.modelSpecsPath.replace(/\/models/, '')}/*`]
    paths['@src/*'] = [`./src/*`]

    if (isPreexistingTsconfig) {
      const types = compilerOptions.types ?? []
      if (!types.includes('vitest/globals')) types.push('vitest/globals')
      compilerOptions.types = types
    }

    fs.writeFileSync(tsconfigPath, JSON.stringify(json, null, 2))
  }
}
