models_path: 'src/app/models'
serializers_path: 'src/app/serializers'
client_api_schema_path: '../client/schema.ts'
conf_path: 'src/app/conf'
migrations_path: 'src/db/migrations'
associations_path: 'src/db/associations.ts'
schema_path: 'src/db/schema.ts'
db_config_path: 'src/conf/env/db.yml'
db_seed_path: 'src/db/seed.ts'
unit_spec_path: 'spec/unit'
feature_spec_path: 'spec/features'
dreamconf_path: 'src/conf/dreamconf.ts'
