strictDepBuilds: false

overrides:
  path-to-regexp: '>=8.4.0'

minimumReleaseAgeExclude:
  - '@rvoh/dream'
  - '@rvoh/dream-spec-helpers'
  - '@rvoh/psychic'
  - '@rvoh/psychic-spec-helpers'
  - '@rvoh/psychic-workers'
  - '@rvoh/psychic-websockets'
